djangoForm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('news/', include('news.urls')),
]

news/urls.py
from django.urls import path
from . import views

app_name = 'news'
urlpatterns = [
    path('', views.index, name='index'),
    path('add/', views.add_post, name='add'),
    path('save/', views.submit_news, name='save'),
    path('email/', views.email_view, name='email'),
    path('process/', views.process, name='process'),
]

news/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=255, blank=False, null=False)
    content = models.CharField(max_length=1000, blank=False, null=False)
    time_create = models.DateTimeField(default=timezone.datetime.now())

news/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'time_create')
        widgets = {
            'title': forms.TextInput(attrs={'class': 'title'}),
            'content': forms.TextInput(attrs={'class': 'content'})
        }


class SendEmail(forms.Form):
    title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'title'}))
    email = forms.EmailField()
    content = forms.CharField(widget=forms.Textarea(attrs={'class': 'content'}))
    cc = forms.BooleanField()

news/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import PostForm, SendEmail


# Create your views here.

def index(request):
    return HttpResponse("xin chao")


def add_post(request):
    a = PostForm()
    return render(request, 'news/add_news.html', {'f': a})


def submit_news(request):
    if request.method == "POST":
        g = PostForm(request.POST)
        if g.is_valid():
            g.save()
            return HttpResponse("Saved")
        else:
            return HttpResponse("not save")
    else:
        return HttpResponse("Don't post request")


def email_view(request):
    b = SendEmail()
    return render(request, 'news/email.html', {'f': b})

#Cach 1
# def process(request):
#     if request.method == "POST":
#         m = SendEmail(request.POST)
#         if m.is_valid():
#             tieude = m.cleaned_data['title']
#             email = m.cleaned_data['email']
#             noidung = m.cleaned_data['content']
#             cc = m.cleaned_data['cc']
#             context = {'tieude': tieude, 'email': email, 'noidung': noidung, 'cc': cc}
#             return render(request, 'news/print_email.html', context)
#         else:
#             return HttpResponse('form not validate')
#     else:
#         return HttpResponse("Don't Post method")


#Cach 2
def process(request):
    if request.method == "POST":
        m = SendEmail(request.POST)
        if m.is_valid():
            context = {'email_view': m}
            return render(request, 'news/print_email.html', context)
        else:
            return HttpResponse('form not validate')
    else:
        return HttpResponse("Don't Post method")

news/templates/news/add_news.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form action="{% url 'news:submit_news' %}" method="post">
        {% csrf_token %}
        <p>{{ f.title }}</p>
        <p>{{ f.content }}</p>
        <input type="submit" value="Add">
    </form>
</body>
</html>

news/templates/news/email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'news:process' %}" method="post">
    {{ f }}
    {% csrf_token %}
    <input type="submit" value="Send Email">
</form>
</body>
</html>

news/templates/news/print_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<table>
    <tr>
        <td>Tieu de</td>
        <td>Email</td>
        <td>Noi dung</td>
        <td>CC</td>
    </tr>
{#    Cach 1#}
{#    <tr>#}
{#        <td>{{ tieude }}</td>#}
{#        <td>{{ email }}</td>#}
{#        <td>{{ noidung }}</td>#}
{#        <td>{{ cc }}</td>#}
{#    </tr>#}

{#    Cach 2#}
        <tr>
        <td>{{ email_view.title }}</td>
        <td>{{ email_view.email }}</td>
        <td>{{ email_view.content }}</td>
        <td>{{ email_view.cc }}</td>
    </tr>
</table>
</body>
</html>